tunnel: fc36bfcb-1381-40ca-b042-d9ed3b0a8724
credentials-file: /root/.cloudflared/fc36bfcb-1381-40ca-b042-d9ed3b0a8724.json
origincert: /root/.cloudflared/cert.pem

ingress:
  - hostname: clickup.ssc.one
    service: http://localhost:8767
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      noHappyEyeballs: true
  - service: http_status:404
