tunnel: 6125a727-b977-4809-9470-bcc6b21dc4b0
credentials-file: /root/.cloudflared/6125a727-b977-4809-9470-bcc6b21dc4b0.json
origincert: /root/.cloudflared/cert.pem

ingress:
  - hostname: clickup.ssc.one
    service: http://localhost:8767
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      noHappyEyeballs: true
  - service: http_status:404
